# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Patch Release
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Next version number'
        required: true
env:
  OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
  OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEYID }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.NEXUS_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test
        run: ./gradlew clean build uploadArchives -PnextVersion=${{ github.event.inputs.nextVersion }}
      - name: Upload to Nexus
        run: ./gradlew uploadArchives -PnextVersion=${{ github.event.inputs.nextVersion }}
      - name: Promote Nexus Release
        run: ./gradlew closeAndReleaseRepository -PnextVersion=${{ github.event.inputs.nextVersion }}
